### ISSUE TITLE
'on' is missing from the type declarations

### ISSUE THREAD

**Issue by daviddelusenet** [react-native-community/react-native-audio-toolkit#227]
<img width="684" alt="Screenshot 2020-06-29 at 11 47 27" src="https://user-images.githubusercontent.com/1398418/85995230-552bff80-b9fe-11ea-8998-8587044136e1.png">

I'm using version `2.0.3`.

**Comment by broberson** [comment]
In the TypeScript type definitions file, there is no entry for Player.on because Player extends EventEmitter3. EventEmitter3 should be installed as a peer dependency in your project, but if it's somehow missing or an older version has been installed, you might get an error like this.

For a really down-and-dirty hackish solution if you've got an angry boss breathing down your neck, you could provide those definitions yourself. You can find them [here](https://github.com/primus/eventemitter3/blob/master/index.d.ts). I'd suggest figuring out what's gone awry with your package management though instead.

**Comment by daviddelusenet** [comment]
Thanks @broberson !

I just installed `EventEmitter3` as a dependency and that solved it indeed 👌
